In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv('heart_failure_clinical_records_dataset.csv')

In [3]:
data

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [4]:
data.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
X = data.drop(columns = ['DEATH_EVENT'])
y = data['DEATH_EVENT']

In [8]:
# Create a model using sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 13)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((239, 12), (60, 12), (239,), (60,))

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [11]:
model.predict(X_train)

array([ 6.58235951e-01,  3.19621351e-01,  9.38445590e-01,  3.68823951e-01,
        2.25255900e-01,  4.76712692e-01,  4.75470111e-01,  1.10365501e-01,
        7.99819716e-01, -2.86763161e-01,  3.37855356e-01,  4.64451767e-01,
        3.70579088e-02,  4.03945066e-01,  2.88621901e-01,  4.95818119e-02,
        9.06493153e-02,  2.67923770e-01,  3.34016612e-02,  5.15291457e-01,
        7.32178397e-01,  1.93006619e-01,  8.37744242e-01,  5.61391345e-02,
        4.81001646e-01,  1.11345142e-01,  3.95232562e-01,  2.46312764e-01,
        4.62050691e-01,  2.19297602e-01,  7.36485884e-01,  3.26953959e-01,
        1.21382110e-01,  4.45030198e-01,  2.19812516e-01,  9.52210855e-01,
       -7.70282096e-02,  1.97747086e-01,  3.59992926e-01,  3.45165025e-01,
        1.50790114e-01,  8.16929131e-01,  2.49069372e-01,  4.33018290e-01,
        9.18478870e-01,  1.87992894e-01,  6.31138568e-01,  7.02781086e-01,
        3.28559688e-01,  2.77863011e-01,  6.34163681e-01,  3.84876350e-01,
        2.10904124e-01,  

In [12]:
model.predict(X_test)

array([-0.12160398,  0.18096602,  0.25255392,  0.57452074,  0.85456776,
        0.78349635,  0.61448154,  0.54217339,  0.52059617, -0.06274607,
        0.20606654,  0.25165185,  0.37181098,  0.53686158,  0.41830707,
       -0.29064301,  0.14000045, -0.0391968 , -0.05557353,  0.06584081,
        0.28094304, -0.24915935, -0.05016423,  1.47901602, -0.07753814,
        0.33117801,  0.02893632,  0.39098136,  0.07054097,  0.28230651,
        0.57193546,  0.378832  , -0.12621303, -0.09069588,  0.49101817,
        0.39872854,  0.17374798,  0.2635837 ,  0.42093315,  0.08024556,
       -0.07721317,  0.00612608,  0.49804661, -0.08953726,  0.08236316,
        0.71994714, -0.07993323,  0.5578567 ,  0.04395367, -0.03562611,
        0.44421687, -0.32271718,  0.40403126,  0.24935618,  0.15268139,
        0.61822652,  0.10697987,  0.57483715,  0.40962598,  0.26629758])

In [13]:
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
    
    mse_train = mean_squared_error(y_train, y_train_pred)
    mse_test = mean_squared_error(y_test, y_test_pred)
    
    mae_train = mean_absolute_error(y_train, y_train_pred)
    mae_test = mean_absolute_error(y_test, y_test_pred)
    
    r2_train = r2_score(y_train, y_train_pred)
    r2_test = r2_score(y_test, y_test_pred)
    
    
    print('Mean Squared Error (Training):', mse_train)
    print('Mean Squared Error (Testing):', mse_test)
    
    print('Mean Absolute Error (Training):', mae_train)
    print('Mean Absolute Error (Testing):', mae_test)
    
    print('Root Mean Square (Training):', r2_train)
    print('Root Mean Square (Testing):', r2_test)
    


Mean Squared Error (Training): 0.13150457697603032
Mean Squared Error (Testing): 0.1137904611154816
Mean Absolute Error (Training): 0.2974461866298393
Mean Absolute Error (Testing): 0.27681454245084525
Root Mean Square (Training): 0.4018416195693716
Root Mean Square (Testing): 0.45814066135484943


In [14]:
def MSE(actual,predictions):
    actual = np.array(actual)
    predictions = np.array(predictions)
    squared_diff = (actual - predictions) ** 2
    mse = np.mean(squared_diff)
    return mse

In [15]:
G = MSE(y_train,y_train_pred)
G

0.13150457697603032

In [16]:
def rmse(y_true, y_pred):
   
    rmse = np.mean((y_true - y_pred) ** 2)
    return np.sqrt(rmse)


rmse_train = rmse(y_train, y_train_pred)
rmse_test = rmse(y_test, y_test_pred)

print("RMSE (Training):", rmse_train)
print("RMSE (Testing):", rmse_test)


RMSE (Training): 0.3626355980540663
RMSE (Testing): 0.3373284172960849


In [17]:
def MAE(y_true, y_pred):
     mae = np.mean(np.abs(y_true - y_pred))
     return mae
     mae_train = mae(y_train, y_train_pred)
     mae_test = mae(y_test, y_test_pred)

print("MAE (Training):", mae_train)
print("MAE (Testing):", mae_test)
    

MAE (Training): 0.2974461866298393
MAE (Testing): 0.27681454245084525


In [18]:
y_test_pred

array([-0.12160398,  0.18096602,  0.25255392,  0.57452074,  0.85456776,
        0.78349635,  0.61448154,  0.54217339,  0.52059617, -0.06274607,
        0.20606654,  0.25165185,  0.37181098,  0.53686158,  0.41830707,
       -0.29064301,  0.14000045, -0.0391968 , -0.05557353,  0.06584081,
        0.28094304, -0.24915935, -0.05016423,  1.47901602, -0.07753814,
        0.33117801,  0.02893632,  0.39098136,  0.07054097,  0.28230651,
        0.57193546,  0.378832  , -0.12621303, -0.09069588,  0.49101817,
        0.39872854,  0.17374798,  0.2635837 ,  0.42093315,  0.08024556,
       -0.07721317,  0.00612608,  0.49804661, -0.08953726,  0.08236316,
        0.71994714, -0.07993323,  0.5578567 ,  0.04395367, -0.03562611,
        0.44421687, -0.32271718,  0.40403126,  0.24935618,  0.15268139,
        0.61822652,  0.10697987,  0.57483715,  0.40962598,  0.26629758])

fearture scaling remaining min,max scalar

In [19]:
def cal_sigma(data):
    data = data.to_numpy()
    mean_data = data.mean()
    sigma_squared = (data - mean_data) ** 2
    sigma_squared_mean = sigma_squared.mean()
    return np.sqrt(sigma_squared_mean)

In [21]:
sigma_of_columns = {c: i for i, c in enumerate(data.columns)}
sigma_of_columns

{'age': 0,
 'anaemia': 1,
 'creatinine_phosphokinase': 2,
 'diabetes': 3,
 'ejection_fraction': 4,
 'high_blood_pressure': 5,
 'platelets': 6,
 'serum_creatinine': 7,
 'serum_sodium': 8,
 'sex': 9,
 'smoking': 10,
 'time': 11,
 'DEATH_EVENT': 12}

In [23]:
for col in list(data):
    sigma_of_columns[col] = cal_sigma(data[col])

In [24]:
sigma_of_columns

{'age': 11.874901429842655,
 'anaemia': 0.49527696249988684,
 'creatinine_phosphokinase': 968.6639668032415,
 'diabetes': 0.49324017403854936,
 'ejection_fraction': 11.815033462318585,
 'high_blood_pressure': 0.4773361502524231,
 'platelets': 97640.54765451424,
 'serum_creatinine': 1.0327786652795918,
 'serum_sodium': 4.405092379513557,
 'sex': 0.4773361502524231,
 'smoking': 0.46688771549471964,
 'time': 77.48430960326975,
 'DEATH_EVENT': 0.46688771549471964}

In [25]:
std = data.std()
type(std)

pandas.core.series.Series

In [27]:
std_scaled_data = data.copy()

In [28]:
for col in list(std_scaled_data):
    mean_of_col = std_scaled_data[col].mean()
    sigma_of_col = sigma_of_columns[col]
    
    for x in std_scaled_data[col]:
        x = (x - mean_of_col)/sigma_of_col

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train.iloc[:, [0,3]] = sc.fit_transform(X_train.iloc[:, [0,3]])
X_test.iloc[:, [0,3]] = sc.transform(X_test.iloc[:, [0,3]])

C:\Users\Rajwardhan\AppData\Local\Temp\ipykernel_23160\4186107798.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.84818893  1.17898261  1.17898261 -0.84818893  1.17898261 -0.84818893
  1.17898261 -0.84818893  1.17898261  1.17898261  1.17898261 -0.84818893
 -0.84818893 -0.84818893  1.17898261  1.17898261 -0.84818893 -0.84818893
  1.17898261  1.17898261 -0.84818893 -0.84818893 -0.84818893  1.17898261
  1.17898261 -0.84818893  1.17898261  1.17898261  1.17898261 -0.84818893
 -0.84818893 -0.84818893 -0.84818893  1.17898261  1.17898261 -0.84818893
 -0.84818893  1.17898261  1.17898261  1.17898261  1.17898261 -0.84818893
 -0.84818893 -0.84818893 -0.84818893 -0.84818893  1.17898261 -0.84818893
 -0.84818893 -0.84818893  1.17898261  1.17898261 -0.84818893  1.17898261
 -0.84818893 -0.84818893 -0.84818893 -0.84818893  1.17898261 -0.84818893
  1.17898261 -0.84818893  1.17898261  1.17898261 -0.84818893 -0.84818893
  1.178