In [1]:
import numpy as np

### What are the properties of a matrix?
##### The properties of matrices are in:
- Matrix Addition
- Scalar Multiplication of Matrix
- Matrix Multiplication
- Transponse Matrix
- And many more

***
### We'll be now reading about the basics of a popular library in Python named 'NumPy'.
#### The most common thing we'll end up doing using 'NumPy' is using arrays
#### We create arrays in NumPy by following method:
***

In [2]:
a = np.array([1, 2])

In [3]:
a

array([1, 2])

---
#### We can check it's type.

In [4]:
type(a)

numpy.ndarray

---
#### But using dtype we get to know what kind of data does it holds.

In [5]:
a.dtype

dtype('int32')

---
#### We can also get the amount of values we have stored in an array.

In [6]:
a.size

2

#### Since we only had two values in it we displayed '2'.

---
#### We can also we the shape of the array

In [7]:
a.shape

(2,)

#### Here the 2 before the comma represents the x demension of the array as it is only a single demensional array.
##### Note: We'll look into this fuction with multiple demensions later on.

---
#### A better way to understand this is by using '.ndim' inbuilt function.

In [8]:
a.ndim

1

#### Just one singular demension

---
## Let's now experiment we two demensional arrays

In [9]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype='int')

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
#### We can use the same functions that we used in above for this two demensional array too.

In [11]:
print(type(b))

<class 'numpy.ndarray'>


In [12]:
b.dtype

dtype('int32')

In [13]:
b.shape

(3, 3)

#### WE can see that the shape now has 'x' and 'y' demensions to display.

In [14]:
b.size

9

In [15]:
b.ndim

2

---
## Let's now experiment we three demensional arrays

In [16]:
c = np.array([[[ 1,  2,  3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]],
               [[19, 20, 21],
                [22, 23, 24],
                [25, 26, 27]]])

In [17]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

#### Again we can use the above used functions for three demensional arrays too.

In [18]:
c.shape

(3, 3, 3)

In [19]:
c.size

27

In [20]:
c.ndim

3

---
## Surprise Test
### Q. Make an three demensional array of shape '(4, 2, 2)'

In [21]:
d = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
                [7, 8]],
              [[9, 10],
               [11, 12]],
              [[13, 14],
               [15, 16]]])

In [22]:
d.shape

(4, 2, 2)

---
## Let's look into different functions
---

#### One can use the 'NumPy' function called 'np.ones()' to generate a matrix filled with ones as per the shape the user wants

In [23]:
np.ones((4, 6, 8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.,

#### One can also use the 'np.full()' function to get a matrix of the shape the user wants with a particular value filled in insted of ones.

In [24]:
np.full(shape = (9, 6), fill_value = 69)

array([[69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69]])

#### One can make a identity matrix with function 'np.identity()'.

In [25]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### Make random numbers whenever you need out of thin air using 'np.random()'

In [26]:
np.random.rand(4,5)

array([[0.5511427 , 0.56162515, 0.42927796, 0.84213541, 0.51292174],
       [0.5072341 , 0.13868395, 0.73341813, 0.9864562 , 0.70370145],
       [0.73712098, 0.83314903, 0.66842604, 0.09355899, 0.87444372],
       [0.3149812 , 0.99028965, 0.50139574, 0.0444585 , 0.90620749]])

#### Usually it returns floats but you can also assign it to only return integers within a specified range

In [27]:
np.random.randint(1, 14, size = (5, 5))

array([[ 2,  2, 10,  9, 13],
       [10,  1, 11,  5,  7],
       [ 9,  5,  8,  1, 11],
       [ 7,  2, 10, 13,  1],
       [10,  9, 13,  5,  9]])

#### If you are tired of constanly getting random numbers you can also seed the random fuction to always return a particular random generation.

In [28]:
np.random.seed(2132004)
set_seed = np.random.randn(7,)
set_seed

array([-0.61912682, -0.69934479,  0.28098204, -0.21230185, -0.73133961,
        0.91127451, -0.31879833])

## Slicing Task / Homework
#### Q. Generate a matrix of shape (3, 3) with only integres where you later on slice the matrix in such a way that it only prints each of it's quadrants

In [29]:
e = np.random.randint(1, 21, size = (3, 3))
e

array([[ 2, 19,  6],
       [20, 18,  9],
       [ 7, 12,  1]])

In [30]:
print(f'First quadrant: \n{e[:2, :2]}\n')
print(f'Second quadrant: \n{e[:2, 1:3]}\n')
print(f'Third quadrant: \n{e[1:, :2]}\n')
print(f'Fourth quadrant: \n{e[1:, 1:3]}')

First quadrant: 
[[ 2 19]
 [20 18]]

Second quadrant: 
[[19  6]
 [18  9]]

Third quadrant: 
[[20 18]
 [ 7 12]]

Fourth quadrant: 
[[18  9]
 [12  1]]


# The End