In [20]:
import numpy as np

In [22]:
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
df = pd.read_csv('vg_data_dictionary.csv')

In [26]:
df

Field                                     Description
0            img        URL slug for the box art at vgchartz.com
1          title                                      Game title
2        console               Console the game was released for
3          genre                               Genre of the game
4      publisher                           Publisher of the game
5      developer                           Developer of the game
6   critic_score                    Metacritic score (out of 10)
7    total_sales              Global sales of copies in millions
8       na_sales      North American sales of copies in millions
9       jp_sales            Japanese sales of copies in millions
10     pal_sales  European & African sales of copies in millions
11   other_sales       Rest of world sales of copies in millions
12  release_date                   Date the game was released on
13   last_update                  Date the data was last updated

In [77]:
a= np.array([[1,2,3,4],
             [2,4,5,6],
             [5,8,9,7]]) #array create

In [79]:
a

array([[1, 2, 3, 4],
       [2, 4, 5, 6],
       [5, 8, 9, 7]])

In [81]:
type(a)

numpy.ndarray

In [83]:
a.dtype

dtype('int32')

In [85]:
a.shape #

(3, 4)

In [87]:
a.ndim #dimensions

2

In [90]:
a2= np.array([[1,2,3,4],
              [2,3,5,6],
              [5,8,5,7]], dtype='int')

In [92]:
a2

array([[1, 2, 3, 4],
       [2, 3, 5, 6],
       [5, 8, 5, 7]])

In [94]:
a.dtype

dtype('int32')

In [96]:
a2.shape

(3, 4)

In [98]:
a2.size

12

In [115]:
w=np.array([[1,2,2],
   [3,6,5]])

In [121]:
w.shape



(2, 3)

In [123]:
w.size

6

In [125]:
w.dtype

dtype('int32')

In [145]:
a3 = np.array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11]]])

In [147]:
a3.shape

(3, 3, 3)

In [149]:
a3

array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11]]])

In [162]:
a4 = np.array([[[1,2],
                [2,3]],
                [[2,4],
                 [6,8]],
                [[4,7],
                 [5,8]],
                [[3,4],
                [4,5]]])

In [164]:
a4.shape

(4, 2, 2)

In [173]:
#3,28,28 ones is used for making large martix(np.'1or0')
np.ones((6,10,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [175]:
np.full(shape = (2,3), fill_value = -3)

array([[-3, -3, -3],
       [-3, -3, -3]])

In [177]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [181]:
#1,10 are the range of the array!
np.random.randint(1,10,size = (4,2,3))

array([[[7, 9, 4],
        [6, 2, 5]],

       [[2, 7, 1],
        [8, 3, 6]],

       [[7, 1, 9],
        [9, 8, 7]],

       [[5, 8, 1],
        [8, 1, 6]]])

In [185]:
#rand values are between 0 and 1 
np.random.rand(5,3,2)

array([[[0.71513969, 0.89049032],
        [0.33315744, 0.92507337],
        [0.41985078, 0.71173904]],

       [[0.48055362, 0.45934695],
        [0.76138614, 0.43877432],
        [0.26705043, 0.90603551]],

       [[0.60761679, 0.08253092],
        [0.85517433, 0.25137364],
        [0.15960441, 0.60905338]],

       [[0.98081027, 0.06815568],
        [0.40423382, 0.71190402],
        [0.28449376, 0.37069402]],

       [[0.9035781 , 0.90439793],
        [0.65009856, 0.02526603],
        [0.34541828, 0.85617391]]])

In [316]:
np.random.seed(112)
dn1 = np.random.randn(5,)
dn1

array([ 1.47773081, -1.31593621,  0.58351335,  0.48563249,  0.341551  ])

In [318]:

dn1[-3:]

array([0.58351335, 0.48563249, 0.341551  ])

In [320]:
dn4 = np.random.randn(5,2)
dn4

array([[ 0.59194622, -0.69941484],
       [-0.2702459 , -0.50714736],
       [ 1.04889264,  1.2737306 ],
       [-0.54326337,  0.09472041],
       [-0.85063974, -0.50512221]])

In [509]:
dn2 = np.random.randint(1,19 , size = (3,3))
dn2

array([[18, 12,  6],
       [18,  3,  5],
       [ 5,  1, 10]])

In [511]:
#slicing
dn2[0:0,1:1] 

array([], shape=(0, 0), dtype=int32)